### ISSUE TITLE
libad_physics_python3 isn't being created.

### ISSUE THREAD

**Issue by tvsrr** [intel/ad-rss-lib#74] opened 2020-04-29 10:27 UTC
The library libad_physics isn't being created. When tried to run "cmake ad_physics" in the dependencies, it throws "**unknown cmake command find_python_binding_package**". There is some issue in generating this python library. 

in the install/ad_physics there is **libad_physics.so** generated but it's not being imported into python.

**Comment by berndgassmann** [comment] 2020-04-29 10:33
You have to explicitly enable the python binding.
So you should either run
 ad_rss$> colcon build --cmake-args -DBUILD_PYTHON_BINDING=ON  -DBUILD_TESTING=ON
Then you finally can also test if the python binding is actually working.

Or you follow the plain CMAKE commands:
https://intel.github.io/ad-rss-lib/BUILDING/index.html#plain-cmake-build
but also there, you have to append the -DBUILD_PYTHON_BINDING=ON to the packages
to achieve the same without colcon...

**Comment by tvsrr** [comment] 2020-04-29 16:15
I tried and it resulted in this error. 
![boost_error](https://user-images.githubusercontent.com/32590292/80619775-c8e37780-8a62-11ea-9f2f-a86316f9fac4.png)

**Comment by berndgassmann** [comment] 2020-04-29 17:45
In travis build on ubuntu 16.04 I see:
-- Boost version: 1.58.0
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.12", minimum required is "2") 
CMake Warning at /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/FindBoost.cmake:1727 (message):
  No header defined for python-py27; skipping header check
Call Stack (most recent call first):
  /home/travis/build/carla-simulator/map/cmake/python-binding.cmake:55 (find_package)
  python/CMakeLists.txt:24 (find_python_binding_packages)
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python-py27
-- PythonLib 2 found. /usr/include/python2.7, /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable version "3.5.2", minimum required is "3") 
CMake Warning at /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/FindBoost.cmake:1727 (message):
  No header defined for python-py35; skipping header check
Call Stack (most recent call first):
  /home/travis/build/carla-simulator/map/cmake/python-binding.cmake:84 (find_package)
  python/CMakeLists.txt:24 (find_python_binding_packages)
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python-py35
--   PYTHON2: Includes: /usr/include/python2.7; Libs: Boost::python-py27;/usr/lib/x86_64-linux-gnu/libpython2.7.so
--   PYTHON3: Includes: /usr/include/python3.5m; Libs: Boost::python-py35;/usr/lib/x86_64-linux-gnu/libpython3.5m.so

**Comment by tvsrr** [comment] 2020-04-30 07:42
Thanks a lot @berndgassmann .. The issue was I was using python3.7 and i think boost 1.58 doesn't support 3.7. I reinstalled with python 3.5. It worked.

**Comment by berndgassmann** [comment] 2020-04-30 09:09
Ok, good that you got down to the root cause of this.
So I'll close this issue.

Bernd.

**Closed by berndgassmann** 2020-04-30 09:09 UTC
